# Generated by Django 2.1.3 on 2018-11-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Img',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_url',
            field=models.ImageField(default=None, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
